# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/ruby/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    device/htc/ruby/prebuilt/lib/libacdbloader.so:obj/lib/libacdbloader.so \
    device/htc/ruby/prebuilt/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
    device/htc/ruby/prebuilt/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
    device/htc/ruby/prebuilt/lib/hw/camera.default.so:obj/lib/hw/camera.vendor.msm8660.so

PRODUCT_COPY_FILES += \
    device/htc/ruby/prebuilt/etc/agps_rm:system/etc/agps_rm \
    device/htc/ruby/prebuilt/etc/vpimg:system/etc/vpimg \
    device/htc/ruby/prebuilt/bin/akmd:system/bin/akmd \
    device/htc/ruby/prebuilt/bin/awb_camera:system/bin/awb_camera \
    device/htc/ruby/prebuilt/bin/calibrator:system/bin/calibrator \
    device/htc/ruby/prebuilt/bin/charging:system/bin/charging \
    device/htc/ruby/prebuilt/bin/ewtzmud:system/bin/ewtzmud \
    device/htc/ruby/prebuilt/bin/htcbatt:system/bin/htcbatt \
    device/htc/ruby/prebuilt/bin/ipd:system/bin/ipd \
    device/htc/ruby/prebuilt/bin/ks:system/bin/ks \
    device/htc/ruby/prebuilt/bin/lsc_camera:system/bin/lsc_camera \
    device/htc/ruby/prebuilt/bin/mpdecision:system/bin/mpdecision \
    device/htc/ruby/prebuilt/bin/netmgrd:system/bin/netmgrd \
    device/htc/ruby/prebuilt/bin/netsharing:system/bin/netsharing \
    device/htc/ruby/prebuilt/bin/port-bridge:system/bin/port-bridge \
    device/htc/ruby/prebuilt/bin/qcks:system/bin/qcks \
    device/htc/ruby/prebuilt/bin/qmiproxy:system/bin/qmiproxy \
    device/htc/ruby/prebuilt/bin/qmuxd:system/bin/qmuxd \
    device/htc/ruby/prebuilt/bin/rmt_storage:system/bin/rmt_storage \
    device/htc/ruby/prebuilt/bin/thermald:system/bin/thermald \
    device/htc/ruby/prebuilt/bin/uimqc:system/bin/uimqc \
    device/htc/ruby/prebuilt/bin/zchgd:system/bin/zchgd \
    device/htc/ruby/prebuilt/xbin/wireless_modem:system/xbin/wireless_modem \
    device/htc/ruby/prebuilt/lib/libacdbloader.so:system/lib/libacdbloader.so \
    device/htc/ruby/prebuilt/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    device/htc/ruby/prebuilt/lib/libaudcal.so:system/lib/libaudcal.so \
    device/htc/ruby/prebuilt/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    device/htc/ruby/prebuilt/lib/libhtc_acoustic.so:system/lib/libhtc_acoustic.so \
    device/htc/ruby/prebuilt/lib/hw/camera.default.so:system/lib/hw/camera.vendor.msm8660.so \
    device/htc/ruby/prebuilt/lib/libcameraface.so:system/lib/libcameraface.so \
    device/htc/ruby/prebuilt/lib/libcamerapp.so:system/lib/libcamerapp.so \
    device/htc/ruby/prebuilt/lib/libgemini.so:system/lib/libgemini.so \
    device/htc/ruby/prebuilt/lib/libidl.so:system/lib/libidl.so \
    device/htc/ruby/prebuilt/lib/libmmipl.so:system/lib/libmmipl.so \
    device/htc/ruby/prebuilt/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    device/htc/ruby/prebuilt/lib/liboemcamera.so:system/lib/liboemcamera.so \
    device/htc/ruby/prebuilt/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    device/htc/ruby/prebuilt/lib/libposteffect.so:system/lib/libposteffect.so \
    device/htc/ruby/prebuilt/lib/libchromatix_mt9d015_default_video.so:system/lib/libchromatix_mt9d015_default_video.so \
    device/htc/ruby/prebuilt/lib/libchromatix_mt9d015_default_zsl.so:system/lib/libchromatix_mt9d015_default_zsl.so \
    device/htc/ruby/prebuilt/lib/libchromatix_mt9d015_preview.so:system/lib/libchromatix_mt9d015_preview.so \
    device/htc/ruby/prebuilt/lib/libchromatix_s5k3h2yx_default_video.so:system/lib/libchromatix_s5k3h2yx_default_video.so \
    device/htc/ruby/prebuilt/lib/libchromatix_s5k3h2yx_hfr.so:system/lib/libchromatix_s5k3h2yx_hfr.so \
    device/htc/ruby/prebuilt/lib/libchromatix_s5k3h2yx_preview.so:system/lib/libchromatix_s5k3h2yx_preview.so \
    device/htc/ruby/prebuilt/lib/libchromatix_s5k3h2yx_zsl.so:system/lib/libchromatix_s5k3h2yx_zsl.so \
    device/htc/ruby/prebuilt/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    device/htc/ruby/prebuilt/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    device/htc/ruby/prebuilt/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    device/htc/ruby/prebuilt/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    device/htc/ruby/prebuilt/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    device/htc/ruby/prebuilt/lib/libC2D2.so:system/lib/libC2D2.so \
    device/htc/ruby/prebuilt/lib/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    device/htc/ruby/prebuilt/lib/libgsl.so:system/lib/libgsl.so \
    device/htc/ruby/prebuilt/lib/libOpenVG.so:system/lib/libOpenVG.so \
    device/htc/ruby/prebuilt/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    device/htc/ruby/prebuilt/lib/libdsm.so:system/lib/libdsm.so \
    device/htc/ruby/prebuilt/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    device/htc/ruby/prebuilt/lib/liboncrpc.so:system/lib/liboncrpc.so \
    device/htc/ruby/prebuilt/lib/libpbmlib.so:system/lib/libpbmlib.so \
    device/htc/ruby/prebuilt/lib/hw/nfc.ruby.so:system/lib/hw/nfc.ruby.so \
    device/htc/ruby/prebuilt/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    device/htc/ruby/prebuilt/lib/libdiag.so:system/lib/libdiag.so \
    device/htc/ruby/prebuilt/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    device/htc/ruby/prebuilt/lib/libdsutils.so:system/lib/libdsutils.so \
    device/htc/ruby/prebuilt/lib/libnetmgr.so:system/lib/libnetmgr.so \
    device/htc/ruby/prebuilt/lib/libnv.so:system/lib/libnv.so \
    device/htc/ruby/prebuilt/lib/libqc-opt.so:system/lib/libqc-opt.so \
    device/htc/ruby/prebuilt/lib/libqdp.so:system/lib/libqdp.so \
    device/htc/ruby/prebuilt/lib/libqmi.so:system/lib/libqmi.so \
    device/htc/ruby/prebuilt/lib/libqmiservices.so:system/lib/libqmiservices.so \
    device/htc/ruby/prebuilt/lib/libqueue.so:system/lib/libqueue.so \
    device/htc/ruby/prebuilt/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    device/htc/ruby/prebuilt/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    device/htc/ruby/prebuilt/lib/hw/sensors.ruby.so:system/lib/hw/sensors.ruby.so \
    device/htc/ruby/prebuilt/lib/libmllite.so:system/lib/libmllite.so \
    device/htc/ruby/prebuilt/lib/libmlplatform.so:system/lib/libmlplatform.so \
    device/htc/ruby/prebuilt/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
    device/htc/ruby/prebuilt/lib/libmpl.so:system/lib/libmpl.so \
    device/htc/ruby/prebuilt/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin \
    device/htc/ruby/prebuilt/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin \
    device/htc/ruby/prebuilt/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin \
    device/htc/ruby/prebuilt/etc/firmware/ti-connectivity/wl1271-nvs.bin:system/etc/firmware/ti-connectivity/wl1271-nvs.bin \
    device/htc/ruby/prebuilt/etc/firmware/firmware.bin:system/etc/wifi/firmware.bin \
    device/htc/ruby/prebuilt/etc/firmware/firmware_ap.bin:system/etc/wifi/firmware_ap.bin \
    device/htc/ruby/prebuilt/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    device/htc/ruby/prebuilt/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    device/htc/ruby/prebuilt/etc/firmware/htc_1271fw.bin:system/etc/firmware/htc_1271fw.bin \
    device/htc/ruby/prebuilt/etc/firmware/htc_1271fw_196_header.bin:system/etc/firmware/htc_1271fw_196_header.bin \
    device/htc/ruby/prebuilt/etc/firmware/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
    device/htc/ruby/prebuilt/etc/firmware/vac_config.ini:system/etc/firmware/vac_config.ini \
    device/htc/ruby/prebuilt/etc/firmware/version:system/etc/firmware/version \
    device/htc/ruby/prebuilt/etc/firmware/WL127x_2.0_2.25.bts:system/etc/firmware/WL127x_2.0_2.25.bts \
    device/htc/ruby/prebuilt/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    device/htc/ruby/prebuilt/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    device/htc/ruby/prebuilt/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    device/htc/ruby/prebuilt/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    device/htc/ruby/prebuilt/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    device/htc/ruby/prebuilt/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    device/htc/ruby/prebuilt/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    device/htc/ruby/prebuilt/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    device/htc/ruby/prebuilt/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw
